# Generated by Django 5.1.2 on 2024-10-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_remove_menu_id'),
    ]

