# Generated by Django 5.1.2 on 2024-10-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Restaurant', '0003_remove_booking_id_alter_booking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                
            
                ('Name', models.CharField(max_length=100)),
                ('No_of_guests', models.IntegerField()),
                ('BookingDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                
                ('Title', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Inventory', models.IntegerField()),
            ],
        ),
    ]
